### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by jamesyoung** [jtremback/avocado#7]
Is there a step prior to npm start?

Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n    at Object.exports._errnoException (util.js:953:11)\n    at exports._exceptionWithHostPort (util.js:976:20)\n    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)"

**Comment by jamesyoung** [comment]
I did not know I needed to run [testrpc](https://github.com/ethereumjs/testrpc) first, which fixed the issue.
